DizzyEggg/pokeemerald

- src/battle_script_commands.c
Status moves that target both opponents will trigger a mon with Clear Body, White Smoke, Hyper Cutter etc. to prevent the loss of stats, but if its partner is targeted first, that partner gets the popup: https://drive.google.com/open?id=1dtTfgxvppD4s2ZL5scPDz9YDf4n7AhMW
This fixes that.
> Minor Doubles ability fixes

- data/battle_scripts_1.s
Better check for valid ally. If there isn't one, the target defaults to the attacker, causing the move to fail.
> Hold Hands fix

- include/constants/pokemon.h
- src/battle_util.c
- src/data/battle_moves.h
Just Moongeist Meme and Sunsteel Strike for now. Added a special flag and modified "GetBattlerAbility" to check the current move for it.
> Ability-ignoring moves

- src/data/battle_moves.h
Title is self-explanatory. As of Gen. 5, Healing Wish and Lunar Dance are affected by Snatch.
> FLAG_SNATCH_AFFECTED for Healing Wish and Lunar Dance

- src/pokemon.c
Fun fact: Before this fix, if you wanted your Pokémon to evolve this way in Faraway Island, it would need to also be at least level 201 ^^;
> Fix for EVO_MAP evolution.

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- include/battle_script_commands.h
- src/battle_script_commands.c
- src/battle_util.c
Also accounts for getting Yawn status and Sunny Day put up right after and then not falling asleep, similar to Insomnia. In USUM, at the end of the turn the mon was Yawned, no message appears that indicates that Leaf Guard prevented it from falling asleep; it just continues as if the mon was never Yawned.
> Implement Leaf Guard.

- src/data/pokemon/pokedex_text.h
- Fixed decap error in Eevee's Pokédex text.
- Fixed missing decap in Mew's Pokédex text.
> Dex Text Fixes

- data/battle_scripts_1.s
For some reason, the battle_engine_v2's battle_scripts_1.s has a lot of pointless tab spaces between the last macro of a BattleScript, and the beginning of the next BattleScript.
It doesn't happen with every single BattleScript, but it does happen with most if not all of the newly implemented BattleScripts that Pokeemerald doesn't have by default.
This annoyed me a little because it was inconsistent. By default, Pokeemerald does not have these worthless tab spaces inbetween BattleScripts, so I decided to correct the battle_engine_v2's battle_scripts_1.s because why not.
> Corrected battle_scripts_1.s

- src/battle_util.c
When a mon with Mold Breaker caused a status move to another one with an Immunity-type ability such as that mon healed immediatly from it, the ability pop up would incorrectly show the for the Mold Breaker mon instead of the Immunity mon.
This affected the following abilities:
- Immunity
- Own Tempo
- Limber
- Insomnia
- Vital Spirit
- Water Veil
- Magma Armor
- Oblivious
Reported by @LOuroboros
> Fixed Ability Pop Up for Immunity-type abilities with Mold Breaker.

- src/battle_util.c
> Make Assurance's power be affected if the opponent hurts themself in confusion

- src/data/battle_moves.h
In Gen2 and Gen4 onwards, Razor Wind has a higher Critical Hit chance.
https://bulbapedia.bulbagarden.net/wiki/Razor_Wind_(move)
> Razor Wind up to Gen4+ standard

- src/data/battle_moves.h
https://bulbapedia.bulbagarden.net/wiki/String_Shot_(move)
> String Shot lowers speed twice from Gen6+

- src/data/battle_moves.h
Source: https://bulbapedia.bulbagarden.net/wiki/Counter_(move)
> Counter affected by Protect, not by Mirror Move

- src/data/battle_moves.h
https://bulbapedia.bulbagarden.net/wiki/Snatch_(move)
- Conversion
- Wish
- Recycle
- Imprison
- Wide Guard
- Quick Guard
- Mat Block
- Magnetic Flux
> Updated moves affected by other moves

- sound/cry_tables.inc
Alolan form cries are the same as their other forms, so they should be compressed.
> Fix Alolan form cries

- src/data/pokemon_graphics/back_pic_coordinates.h
Meowth, Persian, Geodude, Golem, and Grimer were 1-2 pixels too high.
> Fix Alola Form back coordinates

- include/constants/moves.h
Equivalent to #398 for the pokemon_expansion.
The moves are called Teatime and Eternabeam, so certainly, `MOVE_TEA_TIME` and `MOVE_ETERNA_BEAM` are incorrect labels.
> Teatime and Eternabeam should be one word each

- src/data/battle_moves.h
As stated in #411, this move should hurt the opponent and lower their defense, not just the latter.
> Fix Fire Lash

- include/pokemon.h
- src/pokemon.c
Move pokeball structure element to substruct 0 and expand to 5 bits for up to 32 balls. Maintains same pokemon data structure size
> Expand Pokeball Substructure

- src/data/pokemon_graphics/back_pic_coordinates.h
was 1 pixel too high, causing a gap between the sprite and the textbox
> Fix Hoopa Back Sprite Coordinates
