- data/battle_anim_scripts.s
Fixed U-turn's animation freezing. (Relifted the animation from fly, with its new source code)
> Fixed U-turn

- src/data/battle_moves.h
> Update Dive's Base Power

- data/battle_anim_scripts.s
- src/ground.c
Animations for Mud Bomb and Shadow Sneak
> Mud bomb and Shadow Sneak Animations

- data/battle_anim_scripts.s
- include/battle_anim.h
- src/ghost.c
All credit to Doesnt, just stole it from his pokeruby build
Should I put external references at the top of the file??
> Leaf Storm animation

- include/constants/pokemon.h
- src/data/battle_moves.h
Doesn't actually do anything yet but it's there
> Dance flag

- src/data/pokemon/egg_moves.h
Fixes https://github.com/DizzyEggg/pokeemerald/issues/195#issue-491432934
> Fixed the 2 Nidoran having the wrong egg move learnset in egg_moves.h

- src/data/battle_moves.h
> Spark is now Physical

- data/battle_anim_scripts.s
Fixes #249
https://streamable.com/86mjy
> Fixed Charge Beam's animation.

- data/battle_scripts_1.s
- include/battle_script_commands.h
- include/battle_scripts.h
- include/constants/battle_config.h
- src/battle_script_commands.c
- src/battle_util.c
> Disguise ability

- data/battle_scripts_1.s
Fixed the first issue in #294.
> Fixed Damp ability popup

- include/constants/battle_config.h
- src/battle_script_commands.c
- src/wild_encounter.c
Seeing as Battle Engine v2 is adding abilities, I thought it would make sense to include those abilities' overworld effects.
> Overworld effects

- src/data/pokemon/base_stats.h
If anyone finds any issues, let me know.
> Restored the .noFlip parameter to src/data/pokemon/base_stats.h

- src/pokemon.c
- src/wild_encounter.c
- LIGHTNING_ROD
- FLASH_FIRE
- HARVEST
- STORM_DRAIN
- MAGNET_PULL
- INFILTRATOR
- SUPER LUCK
> Added Gen 8 overworld effects.

- src/data/text/move_descriptions.h
Title.
Please, if you have any suggestions to improve them, don't hesitate to bring them up.
> Added descriptions to the moves that were missing one

- src/battle_util.c
Minor correction to the previous commit
> Fix confused mons never hitting themselves

- src/battle_script_commands.c
> battle-engine: fix acupressure crash

- src/data/items.h
> Fix the secondaryId of the Ice and Fighting Gems

- data/battle_anim_scripts.s
- src/battle_anim_effects_1.c
- src/battle_anim_water.c
- fell stinger
- draining kiss
- kings shield (==protect)
- scald
- fire pledge
- water pledge
- grass pledge (WIP)
> anim: add some animation moves

- data/battle_anim_scripts.s
> Fix Nasty Plot move animation

- asm/macros/battle_script.inc
- data/battle_scripts_1.s
- include/battle_script_commands.h
- include/constants/battle_config.h
- include/constants/battle_script_commands.h
- src/battle_pike.c
- src/battle_script_commands.c
- src/battle_util.c
WIP: Going through all moves to see what changed between generations.
> Battle Configs: The Revenge

- src/battle_script_commands.c
> Fixed Regenerator

- include/constants/moves.h
Straight up copied from the battle_engine_v2 branch.
> Defined Gen. 8 Moves

- data/battle_anim_scripts.s
- src/battle_anim.c
- src/battle_anim_electric.c
fix some broken animations
- Drill Run
- Horn Leech
- Heart Stamp
- Spirit Shackle
- Guard Split
- Glaciate
- Bolt Beak
> fix a bunch of anims

- data/battle_anim_scripts.s
> Fixed Dragon Hammer's animation

- src/data/text/item_descriptions.h
> Fixed Eviolite description.

- data/battle_anim_scripts.s
> Fixed Night Daze's animation

- data/battle_anim_scripts.s
> Fixed Trop Kick's animation

- data/battle_anim_scripts.s
> Fixed Freeze Dry's animation

- src/data/battle_moves.h
> Made Throat Chop be affected by Sheer Force

- src/data/battle_moves.h
> Fix Sacred Fire and Fake Out's move data.

- src/data/pokemon_graphics/back_pic_coordinates.h
- src/data/pokemon_graphics/front_pic_coordinates.h
A recent upstream change in pokeemerald had this change, so I also applied it here.
Also added commas where missing.
> Changed pic coordinates from hex to decimal to make it easier to edit.

- test/move_effect_healing_wish.c
Didn't want to waste your time asking you to make these changes, but if you merge this (or something like it) I'll approve the PR over at RHH :)
> Cleanup Healing Wish test syntax
